### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _PQresultMemorySize

### ISSUE THREAD

**Issue by chmich** [ged/ruby-pg#333] opened 2020-03-03 18:40 UTC
pg-gem seems to search the wrong dylib

installed on mac osx

postgres installed by postgres-installer (not homebrew)

[stackoverflow](https://stackoverflow.com/questions/59846019/rails-postgres-dyld-lazy-symbol-binding-failed-symbol-not-found-pqresultme/60513513#60513513)

thanks!
chris

**Comment by larskanis** [comment] 2020-03-03 20:34
Dupe of #332

**Closed** 2020-04-17 19:57 UTC
