### ISSUE TITLE
Saw Rails DB connection pool spike after upgrading from 1.4.6 to 1.5.2

### ISSUE THREAD

**Issue by jeffbax** [ged/ruby-pg#532] opened 2023-04-27 22:43 UTC
Running in a Rails 6.1 / Ruby 3.1 application, was suddenly flooded with errors like:

```
ActiveRecord::ConnectionTimeoutError
could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use

ActiveRecord::ConnectionNotEstablished
connection to server at "xx.xx.xx.xx", port 5432 failed: FATAL: remaining connection slots are reserved for non-replication superuser connections
```

and I noticed active connections really spiking in Heroku

<img width="359" alt="Screenshot 2023-04-27 at 6 42 31 PM" src="https://user-images.githubusercontent.com/489946/235006345-da2725e1-2d5d-4c95-95ee-047fec03a3dd.png">

Not exactly sure what exactly might have changed, I suspect maybe something involving this line in history.md?
* PG::Connection is not shareable and must be created within each Ractor to establish a dedicated connection.

Just wondering if there are any further explanations, as in the meantime I had to rush a downgrade (maybe it is a Rails issue, but figured I would raise something here in case anyone else noticed something similar)

**Comment by larskanis** [comment] 2023-04-28 05:26
Sorry you're having problems, but I doubt that they are caused by ruby-pg. Pg-1.5 didn't change anything essential regarding connection setup and teardown.

The error message indicates that the ActiveRecord connection pool is running out, so some rails or application code doesn't return the connection back. That looks like an issue on a higher level than ruby-pg.

**Comment by jeffbax** [comment] 2023-04-28 14:19
Yeah I mean, I understand that it is coming from Rails, but the _only_ difference I made was upgrading the PG gem version so I'm kind of scratching my head at what else it could be.

Since reverting the app back to 1.4.6, the pool has since stabilized around ~90 where it normally sits in comparison to trying to break 500 and max out the database. Would be curious if anyone else has observed something similar at least.

It certainly could be my own rails config, or maybe Rails 6.1 isn't able to use this version of pg but figured I would at least make not of it here in case anyone else ran into similar, since I don't have anything else to look at currently.

**Comment by larskanis** [comment] 2023-04-28 15:36
OK, your first message sounded like you updated a bunch of gems at once and not just pg. Could you please double check, that it was only pg that was updated?

I reviewed the code changes to PG::Connection and they aren't too many since 1.4.6 and they don't fit to your issue description. Rails-6.1 and ruby-3.1 should work with pg-1.5 without restrictions.

In the meantime I released pg-1.5.3, with two minor fixes. Can you find any indication in the logs where the problem originates?

**Comment by jeffbax** [comment] 2023-04-28 16:22
Sorry for the confusion, yeah the only changes were my PG gem version.

I'm scanning my application logs, but it seems like whatever is going on is getting swallowed by active record at the moment. At least there is nothing sticking out that looks like it is coming from the gem or more than the generic errors I put at the top.

the Postgres logging is mostly just sampling and showing the connections swinging a lot, but no culprit yet although I will keep trying to dig around

**Comment by larskanis** [comment] 2024-03-04 17:35
Closing since there seems to be no progress.

**Closed by larskanis** 2024-03-04 17:35 UTC
